### ISSUE TITLE
App window position on a desktop

### ISSUE THREAD

**Issue by abirger** [remoteit/desktop#15]
On Windows 7, the app window initially opens in the middle of the screen. However, when the app is invoked with the icon in Notification Area, the app's window opens too far to the left, so the buttons under "Settings" could be barely seen. The window cannot be dragged in a different position, which is very inconvenient.

**Comment by abirger** [comment]
Actually, the bug with a window position stays even after upgrade the Windows 10. I re-install the app hoping that it would fix the position error but no, the app behavior is still wrong.

At start, it opens in the middle of screen; however, as soon as the app window goes to a background (gets overlapped by other app windows), the app window moves too far to the left. The only way to move the window to a somewhat acceptable position is to press "Win+Arrow Up".

**Comment by JamieRuderman** [comment]
Thanks for the feedback, the latest release changes how the window works so that it's a floating window that you can position anywhere. This should address your issue. Cheers.
