### ISSUE TITLE
Get connection error

### ISSUE THREAD

**Issue by tengshan2008** [remoteit/desktop#20]
Connection to peer failed (failed p2p connect) (CODE: 21)

Use desktop app(Version: v2.3.21) on windows 10

Remote ssh raspberrypi in home.

**Comment by lowerpower** [comment]
This is because a P2P connection could not be negotiated between the desktop and the remote peer, we are working on fail-over to proxy servers in this case, this will be in a future release.

**Comment by tengshan2008** [comment]
OK
